# =========================
# Step 1: Build Angular app
# =========================
FROM node:20 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build -- --configuration production

# =========================
# Step 2: Serve with Nginx
# =========================
FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

# ✅ FIXED PATH
COPY --from=build /app/dist/frontend/browser/ /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]